# Generated by Django 4.1.1 on 2022-10-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(default='null', max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('tag', models.CharField(default='null', max_length=255)),
                ('time_created', models.DateTimeField(null=True)),
                ('time_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
